Repository whatever-mentoring/Whatssue-BE, pull requests merged in 2023-09, with the labels that each got.

#1 [Docs/#2] Issue Template Settings
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 📜Docs, 이해송

#4 [Docs/#3] PR Template Settings
  .github/.github/PULL_REQUEST_TEMPLATE.md
Labels: 📜Docs, 이해송

#5 [feature/WHAT-36] Mysql 연동
  .gitignore
  build.gradle
  src/main/java/gdg/whatssue/entity/Admin.java
  src/main/resources/application.properties
Labels: ✨Feat, 김준영

#7 [WHAT-26] CI file configure
  .github/workflows/gradle.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🖥️Deploy, 이해송

#9 [WHAT-43] 일정/출석/공결관리 스켈레톤 Api 작성
  .gitignore
  src/main/java/gdg/whatssue/controller/AbsentControllerImpl.java
  src/main/java/gdg/whatssue/controller/AttendanceControllerImpl.java
  src/main/java/gdg/whatssue/controller/ScheduleControllerImpl.java
  src/main/java/gdg/whatssue/controller/inter/AbsentController.java
  src/main/java/gdg/whatssue/controller/inter/AttendanceController.java
  src/main/java/gdg/whatssue/controller/inter/ScheduleController.java
Labels: ✨Feat, 김준영

#10 [WHAT-110] cd file 작성 & dockerfile 작성
  .github/workflows/cd_server.yml
  Dockerfile
Labels: 🖥️Deploy, 이해송

#13 [WHAT-110] : fix java version
  .github/workflows/cd_server.yml
  .github/workflows/gradle.yml
  Dockerfile
Labels: 🖥️Deploy, 이해송

#14 [WHAT-110]fix : docker images name -> lowercase
  .github/workflows/cd_server.yml
Labels: 🖥️Deploy, 이해송

#15 [WHAT-110] fix : command error fix
  .github/workflows/cd_server.yml
Labels: 🖥️Deploy, 이해송

#16 [WHAT-110]fix : token 환경변수 이름 수정
  .github/workflows/cd_server.yml
Labels: 🖥️Deploy, 이해송

#17 [WHAT-110]fix : application.yml 에 값 전달
  .github/workflows/cd_server.yml
Labels: 🖥️Deploy, 이해송

#20 [WHAT-110]
  .github/workflows/cd_server.yml
Labels: 🖥️Deploy, 이해송

#21 [WHAT-110]
  .github/workflows/cd_server.yml
Labels: 🖥️Deploy, 이해송

#22 [WHAT-110]fix:fix delete images name
  .github/workflows/cd_server.yml
Labels: 🖥️Deploy, 이해송

#26 [WHAT-75]feat : 수정, 삭제 완료
  src/main/java/gdg/whatssue/controller/ScheduleControllerImpl.java
  src/main/java/gdg/whatssue/controller/inter/ScheduleController.java
  src/main/java/gdg/whatssue/entity/Schedule.java
  src/main/java/gdg/whatssue/service/ScheduleService.java
Labels: ✨Feat, 이해송

#27 [WHAT-75]fix : import 문 빼먹음
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/gdg/whatssue/controller/inter/ScheduleController.java
Labels: ✨Feat, 이해송

#28 [WHAT-75]fix : workflow modify
  .github/workflows/cd_server.yml
  .github/workflows/gradle.yml
Labels: 🐞BugFix, ✨Feat, 이해송

#30 [WHAT -128]Feature/what 128
  build.gradle
  src/main/java/gdg/whatssue/controller/AbsentControllerImpl.java
  src/main/java/gdg/whatssue/controller/inter/AbsentController.java
  src/main/java/gdg/whatssue/entity/ApplyOfficialAbsent.java
  src/main/java/gdg/whatssue/entity/Schedule.java
  src/main/java/gdg/whatssue/mapper/AbsentRequestMapper.java
  src/main/java/gdg/whatssue/mapper/GenericMapper.java
  src/main/java/gdg/whatssue/mapper/ScheduleDetailMapper.java
  src/main/java/gdg/whatssue/repository/ScheduleRepository.java
  src/main/java/gdg/whatssue/service/AbsentService.java
  src/main/java/gdg/whatssue/service/ScheduleService.java
  src/main/java/gdg/whatssue/service/dto/AbsentListDto.java
  src/main/java/gdg/whatssue/service/dto/AbsentRequestDto.java
Labels: ✨Feat, 이해송

#31 [WHAT-128]fix : ci file 수정, 오류 해결
  .github/workflows/gradle.yml
  src/main/java/gdg/whatssue/controller/inter/AbsentController.java
Labels: 🐞BugFix, 이해송

#34 Update CODEOWNERS
  .github/CODEOWNERS
Labels: 📜Docs, 이해송

#38 [WHAT-136]Fix/what 136
  .github/workflows/gradle.yml
  src/main/java/gdg/whatssue/controller/AbsentControllerImpl.java
  src/main/java/gdg/whatssue/entity/ApplyOfficialAbsent.java
  src/main/java/gdg/whatssue/mapper/GenericMapper.java
  src/main/java/gdg/whatssue/service/AbsentService.java
  src/main/java/gdg/whatssue/service/ScheduleService.java
  src/test/java/gdg/whatssue/WhatssueApplicationTests.java
Labels: 🐞BugFix, 이해송

#40 [WHAT-121] user는 모임 수정과 생성이 가능하다
  src/main/java/gdg/whatssue/controller/AdminControllerImpl.java
  src/main/java/gdg/whatssue/controller/inter/AdminController.java
  src/main/java/gdg/whatssue/entity/Club.java
  src/main/java/gdg/whatssue/service/AdminService.java
  src/main/java/gdg/whatssue/service/dto/ClubDetailDto.java
Labels: ✨Feat, 이해송

#41 [WHAT-140] 수정
  src/main/java/gdg/whatssue/service/AbsentService.java
  src/main/java/gdg/whatssue/service/dto/AbsentListDto.java
Labels: 🐞BugFix, 이해송

#42 [WHAT-118] [WHAT-93] 가입 요청 리스트 조회 api
  src/main/generated/gdg/whatssue/mapper/AbsentRequestMapperImpl.java
  src/main/generated/gdg/whatssue/mapper/ScheduleDetailMapperImpl.java
  src/main/java/gdg/whatssue/ClubIdConst.java
  src/main/java/gdg/whatssue/WhatssueApplication.java
  src/main/java/gdg/whatssue/controller/MemberControllerImpl.java
  src/main/java/gdg/whatssue/controller/inter/MemberController.java
  src/main/java/gdg/whatssue/entity/ClubJoinRequest.java
  src/main/java/gdg/whatssue/repository/ClubJoinRequestRepository.java
  src/main/java/gdg/whatssue/service/MemberService.java
  src/main/java/gdg/whatssue/service/dto/ClubJoinRequestListDto.java
Labels: ✨Feat, 김준영

#43 [WHAT-88] 가입 요청 수락 거절
  src/main/generated/gdg/whatssue/mapper/ScheduleDetailMapperImpl.java
  src/main/java/gdg/whatssue/controller/MemberControllerImpl.java
  src/main/java/gdg/whatssue/entity/Club.java
  src/main/java/gdg/whatssue/entity/ClubMemberMapping.java
  src/main/java/gdg/whatssue/entity/Member.java
  src/main/java/gdg/whatssue/repository/ClubMemberMappingRepository.java
  src/main/java/gdg/whatssue/service/MemberService.java
  src/main/resources/application.yml
Labels: ✨Feat, 김준영

#45 [WHAT-95] 전체 멤버 및 멤버별 출공결 현황 조회
  src/main/java/gdg/whatssue/controller/MemberControllerImpl.java
  src/main/java/gdg/whatssue/entity/CheckedListByUser.java
  src/main/java/gdg/whatssue/entity/Member.java
  src/main/java/gdg/whatssue/service/MemberService.java
  src/main/java/gdg/whatssue/service/dto/ClubMemberListDto.java
  src/main/resources/application.yml
Labels: ✨Feat, 김준영

#50 [WHAT-147]feat: 출석 테이블에 공결 update
  src/main/java/gdg/whatssue/entity/AttendanceByUserBySchedule.java
  src/main/java/gdg/whatssue/repository/AttendanceByUserByScheduleRepository.java
  src/main/java/gdg/whatssue/service/AbsentService.java
Labels: 🐞BugFix, ✨Feat, 이해송

#51 [WHAT-60] 초대 링크 삭제/조회/생성 & 가입신청/가입신청창
  src/main/java/gdg/whatssue/controller/AdminControllerImpl.java
  src/main/java/gdg/whatssue/controller/MemberControllerImpl.java
  src/main/java/gdg/whatssue/controller/inter/AdminController.java
  src/main/java/gdg/whatssue/controller/inter/MemberController.java
  src/main/java/gdg/whatssue/entity/Club.java
  src/main/java/gdg/whatssue/entity/ClubJoinRequest.java
  src/main/java/gdg/whatssue/mapper/ClubDetailMapper.java
  src/main/java/gdg/whatssue/repository/LinkRepository.java
  src/main/java/gdg/whatssue/service/AdminService.java
  src/main/java/gdg/whatssue/service/MemberService.java
  src/main/java/gdg/whatssue/service/dto/LinkDetailDto.java
  src/main/java/gdg/whatssue/service/dto/LinkInfoDto.java
  src/main/java/gdg/whatssue/service/dto/LinkResultDto.java
Labels: ✨Feat, 이해송

#53 [WHAT-115] 회원가입시 ID 중복체크
  src/main/java/gdg/whatssue/controller/UserControllerImpl.java
  src/main/java/gdg/whatssue/controller/inter/UserController.java
  src/main/java/gdg/whatssue/service/UserService.java
  src/main/java/gdg/whatssue/service/dto/CheckIdDuplicateDto.java
Labels: ✨Feat, 김준영

#58 [WHAT-88] 멤버 모입 가입 시 출결 현황 생성
  build.gradle
  src/main/generated/gdg/whatssue/mapper/AbsentRequestMapperImpl.java
  src/main/generated/gdg/whatssue/mapper/ClubDetailMapperImpl.java
  src/main/generated/gdg/whatssue/mapper/ScheduleDetailMapperImpl.java
  src/main/java/gdg/whatssue/configuration/SecurityConfig.java
  src/main/java/gdg/whatssue/entity/CheckedListByUser.java
  src/main/java/gdg/whatssue/filter/JwtTokenFilter.java
  src/main/java/gdg/whatssue/repository/CheckedListByUserRepository.java
  src/main/java/gdg/whatssue/service/MemberService.java
  src/main/java/gdg/whatssue/service/UserService.java
  src/main/java/gdg/whatssue/util/JwtTokenUtil.java
Labels: ✨Feat, 김준영

#60 [WHAT-165]fix : pathvariable 로 수정
  src/main/java/gdg/whatssue/controller/AdminControllerImpl.java
  src/main/java/gdg/whatssue/controller/MemberControllerImpl.java
  src/main/java/gdg/whatssue/controller/inter/MemberController.java
  src/main/java/gdg/whatssue/service/MemberService.java
Labels: 🐞BugFix, 이해송

#61 [WHAT-73] security & jwt 토큰을 이용한 로그인 구현
  build.gradle
  src/main/generated/gdg/whatssue/mapper/AbsentRequestMapperImpl.java
  src/main/generated/gdg/whatssue/mapper/ClubDetailMapperImpl.java
  src/main/generated/gdg/whatssue/mapper/ScheduleDetailMapperImpl.java
  src/main/java/gdg/whatssue/configuration/SecurityConfig.java
  src/main/java/gdg/whatssue/configuration/WebConfig.java
  src/main/java/gdg/whatssue/controller/MemberControllerImpl.java
  src/main/java/gdg/whatssue/controller/UserControllerImpl.java
  src/main/java/gdg/whatssue/controller/inter/MemberController.java
  src/main/java/gdg/whatssue/controller/inter/UserController.java
  src/main/java/gdg/whatssue/filter/JwtTokenFilter.java
  src/main/java/gdg/whatssue/repository/MemberRepository.java
  src/main/java/gdg/whatssue/service/UserService.java
  src/main/java/gdg/whatssue/service/dto/UserLoginDto.java
  src/main/java/gdg/whatssue/util/JwtTokenUtil.java
Labels: ✨Feat, 김준영

#62 [WHAT-73] 스프링 부트 실행 에러 해결
  src/main/java/gdg/whatssue/controller/inter/MemberController.java
Labels: 🐞BugFix, 김준영

#63 [WHAT-169]Feature/what 169
  src/main/java/gdg/whatssue/controller/AccountingControllerImpl.java
  src/main/java/gdg/whatssue/controller/inter/AccountingController.java
  src/main/java/gdg/whatssue/entity/MoneyBook.java
  src/main/java/gdg/whatssue/mapper/AbsentRequestMapper.java
  src/main/java/gdg/whatssue/mapper/GenericMapper.java
  src/main/java/gdg/whatssue/mapper/MoneyBookCreateMapper.java
  src/main/java/gdg/whatssue/mapper/MoneyBookListMapper.java
  src/main/java/gdg/whatssue/repository/MoneyBookRepository.java
  src/main/java/gdg/whatssue/service/AccountService.java
  src/main/java/gdg/whatssue/service/dto/AccountBookCreateDto.java
  src/main/java/gdg/whatssue/service/dto/AccountBookListDto.java
Labels: ✨Feat, 이해송

#64 [WHAT-166] swagger 관련 api 권한 인증에서 제외
  src/main/generated/gdg/whatssue/mapper/AbsentRequestMapperImpl.java
  src/main/generated/gdg/whatssue/mapper/ClubDetailMapperImpl.java
  src/main/generated/gdg/whatssue/mapper/MoneyBookCreateMapperImpl.java
  src/main/generated/gdg/whatssue/mapper/MoneyBookListMapperImpl.java
  src/main/generated/gdg/whatssue/mapper/ScheduleDetailMapperImpl.java
  src/main/java/gdg/whatssue/configuration/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🐞BugFix, 김준영

#65 [WHAT-88] fix: 가입 요청 수락 시 에러 해결
  src/main/java/gdg/whatssue/entity/CheckedListByUser.java
  src/main/java/gdg/whatssue/entity/ClubMemberMapping.java
  src/main/java/gdg/whatssue/entity/Member.java
  src/main/java/gdg/whatssue/service/MemberService.java
  src/main/resources/application.yml
Labels: 🐞BugFix, 김준영

#69 [WHAT-169]Feature/what 169
  src/main/java/gdg/whatssue/controller/AbsentControllerImpl.java
  src/main/java/gdg/whatssue/controller/AccountingControllerImpl.java
  src/main/java/gdg/whatssue/controller/inter/AbsentController.java
  src/main/java/gdg/whatssue/entity/MoneyBook.java
  src/main/java/gdg/whatssue/repository/AttendanceByUserByScheduleRepository.java
  src/main/java/gdg/whatssue/repository/LinkRepository.java
  src/main/java/gdg/whatssue/repository/MemberRepository.java
  src/main/java/gdg/whatssue/repository/MoneyBookRepository.java
  src/main/java/gdg/whatssue/service/AbsentService.java
  src/main/java/gdg/whatssue/service/AccountService.java
  src/main/java/gdg/whatssue/service/AdminService.java
  src/main/java/gdg/whatssue/service/ScheduleService.java
  src/main/java/gdg/whatssue/service/dto/AbsentRequestDto.java
  src/main/java/gdg/whatssue/service/dto/AccountBookCreateDto.java
  src/main/java/gdg/whatssue/service/dto/LinkDetailDto.java
  src/main/java/gdg/whatssue/service/dto/LinkResultDto.java
Labels: 🐞BugFix, 이해송

#70 [WHAT-169]Feature/what 169
  src/main/java/gdg/whatssue/controller/AbsentControllerImpl.java
  src/main/java/gdg/whatssue/entity/MoneyBook.java
  src/main/java/gdg/whatssue/repository/MoneyBookRepository.java
  src/main/java/gdg/whatssue/service/AccountService.java
  src/main/java/gdg/whatssue/service/AdminService.java
Labels: 🐞BugFix, 이해송

#71 [WHAT-169] 링크 수정 및 입출금 CRUD
  src/main/java/gdg/whatssue/controller/AdminControllerImpl.java
  src/main/java/gdg/whatssue/controller/inter/AdminController.java
  src/main/java/gdg/whatssue/entity/Link.java
  src/main/java/gdg/whatssue/service/AdminService.java
  src/main/java/gdg/whatssue/service/dto/LinkInfoDto.java
Labels: 🐞BugFix, 이해송

#72 [WHAT-169]
  src/main/java/gdg/whatssue/repository/MoneyBookRepository.java
  src/main/java/gdg/whatssue/service/AccountService.java
Labels: 🐞BugFix, 이해송

#75 [WHAT-169] 클럽 - MoneyBook 관계 수정
  src/main/java/gdg/whatssue/entity/Club.java
  src/main/java/gdg/whatssue/entity/MoneyBook.java
  src/main/java/gdg/whatssue/service/AccountService.java
Labels: 🐞BugFix, 이해송

#83 [WHAT-174] 공결 fix 완료
  src/main/java/gdg/whatssue/entity/ApplyOfficialAbsent.java
  src/main/java/gdg/whatssue/entity/Schedule.java
  src/main/java/gdg/whatssue/service/AbsentService.java
Labels: 🐞BugFix, 이해송
